import { ProjectsSectionType } from '@/lib/types/sections';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects & achievements',
  projects: [
    {
      id: 'multi-task-fire-bot',
      name: 'Multi Task Fire Bot',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1561144257-e32e8efc6c4f',
      year: 2024,
      tags: ['Robotics', 'Fire Safety', 'Automation'],
    },
    {
      id: 'hydrogen-propulsion-combustion',
      name: 'Hydrogen Propulsion and Combustion System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
      year: 2024,
      tags: ['Aerospace', 'Hydrogen', 'Propulsion'],
    },
    {
      id: 'xaziuo-cyber-security',
      name: 'Xaziuo: Cyber Security Module',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f',
      year: 2024,
      tags: ['Cybersecurity', 'Software', 'Protection'],
    },
    {
      id: 'electromagnetic-pulsar',
      name: 'Electro Magnetic Pulsar System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1580983218765-f663bec07b37',
      year: 2024,
      tags: ['Electronics', 'Electromagnetic', 'Systems'],
    },
    {
      id: '360-radar-sensing',
      name: '360 Radar Sensing System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485',
      year: 2024,
      tags: ['Radar', 'Sensing', 'Detection'],
    },
    {
      id: 'military-surveillance-bot',
      name: 'Military Surveillance and Defence Bot',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0',
      year: 2024,
      tags: ['Military', 'Surveillance', 'Defense'],
    },
    {
      id: 'econanofilter-water',
      name: 'EcoNanoFilter Water Purification',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1509391366360-2e959784a276',
      year: 2023,
      tags: ['Research', 'Water', 'Nanotechnology'],
    },
    {
      id: 'protirodh-biokit-health',
      name: 'Protirodh Biokit Health System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1510878933023-e2e2e3942fb0',
      year: 2023,
      tags: ['Healthcare', 'Biokit', 'Rural Health'],
    },
    {
      id: 'floating-seedbed-desalination',
      name: 'Floating Seedbed Desalination System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1601612628452-9e99ced43524',
      year: 2023,
      tags: ['Agriculture', 'Desalination', 'Sustainability'],
    },
    {
      id: 'aviation-energy-integration',
      name: 'Aviation Energy System',
      url: '#',
      repo: '#',
      img: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b',
      year: 2023,
      tags: ['Aviation', 'Energy', 'Integration'],
    },
    {
      id: 'mhd-engine-underwater',
      name: 'MHD Engine for Underwater Vehicles',
      url: '#',
      repo: '#',
      img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
      year: 2023,
      tags: ['MHD', 'Underwater', 'Propulsion'],
    },
  ],
};
